name: Deploy To Edgio (sveltekit.rishi.app)

on:
  workflow_dispatch:

jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: curl -X POST $VERCEL_HOOK
        env:
            VERCEL_HOOK: ${{secrets.VERCEL_HOOK}}
